### ISSUE TITLE
Issue with this add-on and the Captcha in PMPro checkout

### ISSUE THREAD

**Issue by talkytoaster** [strangerstudios/pmpro-multiple-memberships-per-user#100]
Hi,

I use the multiple membership add-on with PMPro, and I have found an issue when Captcha is enabled and the customer is logged in, and they try to purchase the add-on subscription/membership, there is NO Captcha shown, and when they try to check out they get a Captcha error:

reCAPTCHA failed. (missing-input) Please try again

Can this please be fixed? At the moment, due to this issue, I have had to disable the Captcha option in PMPro on my site (again).

**Comment by ideadude** [comment]
Fixed by #105 and #930d680f82a86ddf09208d15e568144e628b49d7
