### ISSUE TITLE
Default level not pulled from Membership Checkout Form block if set

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-multiple-memberships-per-user#116]
If there is no level / levels attribute in the URL, the default level assigned to the checkout form via block settings is not respected.

@dparker1005 wrote a simple recipe to force this behavior for our Stranger Studios site. We should consider a way to have this behavior built into MMPU. Similarly, we should consider supporting the [pmpro_checkout] shortcode in page where there is a [meta field pmpro_default_level as respected in PMPro core](https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/functions.php#L2354).

```
function my_pmprommpu_pull_checkout_level_from_checkout_block( $checkout_level ) {
	global $pmpro_checkout_level_ids;
	if( empty( $pmpro_checkout_level_ids ) && ! empty( $checkout_level->id ) ) {
		$pmpro_checkout_level_ids = array( $checkout_level->id );
	}
}
add_action( 'pmpro_checkout_preheader_after_get_level_at_checkout', 'my_pmprommpu_pull_checkout_level_from_checkout_block', 10, 1 );
```

**Comment by mircobabini** [comment]
There's a PR for that.

https://github.com/strangerstudios/pmpro-multiple-memberships-per-user/pull/114

**Comment by michaelbeil** [comment]
A customer (ticket 426526) reported this:

> Uncaught TypeError: implode(): Argument #1 ($pieces) must be of type array, string given in /nas/content/live/-/wp-content/plugins/pmpro-multiple-memberships-per-user/pages/checkout.php:48
Stack trace:
#0 /nas/content/live/-/wp-content/plugins/pmpro-multiple-memberships-per-user/pages/checkout.php(48): implode('+', NULL)
1 /nas/content/live/-/wp-content/plugins/paid-memberships-pro/includes/functions.php(384): include('/nas/content/li...')
2 /nas/content/live/-/wp-content/plugins/paid-memberships-pro/includes/init.php(85): pmpro_loadTemplate('checkout', 'local', 'pages')
3 /nas/content/live/-/wp-includes/shortcodes.php(356): pmpro_pages_shortcode('', '', 'pmpro_checkout')
4 [internal function]: do_shortcode_tag(Array)
5 /nas/content/live/-/wp-includes/shortcodes.php(228): preg_replace_callback('/\\[(\\[?)(show_s...', 'do_shortcode_ta...', '[pmpro_checkout...')
6 /nas/content/live/-/wp-includes/class-wp-hook.php(307): do_shortcode('[pmpro_checkout...')
7 /nas/content/live/-/wp-includes/plugin.php(191): WP_Hook->apply_filters('[pmpro_checkout...', Array)
8 /nas/content/live/-/wp-includes/post-template.php(253): apply_filters('the_content', '
[pmpro_check...')
9 /nas/content/live/-/wp-content/plugins/elementor/modules/page-templates/module.php(190): the_content()
10 [internal function]: Elementor\Modules\PageTemplates\Module->print_callback()
11 /nas/content/live/-/wp-content/plugins/elementor/modules/page-templates/module.php(207): call_user_func(Array)
12 /nas/content/live/-/wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php(19): Elementor\Modules\PageTemplates\Module->print_content()
13 /nas/content/live/-/wp-includes/template-loader.php(106): include('/nas/content/li...')
14 /nas/content/live/-/wp-blog-header.php(19): require_once('/nas/content/li...')
15 /nas/content/live/-/index.php(17): require('/nas/content/li...')
16 {main}
  thrown

Sent the PR.
