### ISSUE TITLE
New pmpro changes

### ISSUE THREAD

**Issue by apzrn** [strangerstudios/pmpro-multiple-memberships-per-user#132]
Hi will there be an update coming to this plugin? There seems to be an issue with some functions after the new update: ![image](https://github.com/strangerstudios/pmpro-multiple-memberships-per-user/assets/85966982/21d3534a-35aa-4b7c-a667-611fcec40b58)

**Comment by Square-Lines** [comment]
Hello,

PMPro v3.0 incorporates much of the functionality of this plugin, with some exceptions (*). So in most cases, you will no longer need this plugin after updating to version 3.0.

(*) A primary exception is that the v3.0 implementation of MMPU does not allow for multiple disparate subscriptions to be purchased in the same checkout. If you need that, there is a legacy plugin that brings that functionality back for Stripe onsite and Braintree - that can be found at https://www.paidmembershipspro.com/add-ons/pmpro-mmpu-legacy/ . 

-Aaron

**Comment by apzrn** [comment]
Ohh that’s epic, are any of: Add PayPal Express Add On, Variable Pricing Add On, and Payment Plans Add On no longer necessary?
