### ISSUE TITLE
Problem with backticks in queries

### ISSUE THREAD

**Issue by itibet** [strangerstudios/pmpro-multiple-memberships-per-user#2]
Hi,
MySql (5.5.53/Linux) complains about backtics in queries, e.g. this is the error I get when opening page "Membership Levels":

`
WordPress database error Unknown column 'mlg.group' in 'field list' for query SELECT `mlg.group` FROM wp_pmpro_membership_levels_groups mlg WHERE `level` = -1
`

I had to remove all backticks in pmpro-multiple-memberships-per-user/includes/functions.php to make it work.
Thank you

**Comment by dchenk** [comment]
I'm getting the same exact error!

**Comment by itibet** [comment]
Hi,
mysql doesn't like backticks in queries, to make the plugin work open "pmpro-multiple-memberships-per-user/includes/functions.php" with a text editor and remove all occurrences of `.
E.g. the following string
"SELECT `mlg.group` FROM {$wpdb->pmpro_membership_levels_groups} mlg WHERE `level` = %d"
should be replaced with
"SELECT mlg.group FROM {$wpdb->pmpro_membership_levels_groups} mlg WHERE level = %d"
Bye

**Comment by dchenk** [comment]
In the file includes/functions.php there are two instances where the backticks on "mlg.group" are causing errors. I had to remove both, and I suspect such backticks also caused an error for me just now when the plugin allowed a user to register for a second level in the group where they're only allowed one level at a time. The plugin was supposed to cancel the user's membership to the previous level.

Please fix this asap! Thanks a lot.

**Comment by eighty20results** [comment]
Pull request to resolve this issue: https://github.com/strangerstudios/pmpro-multiple-memberships-per-user/pull/5
