### ISSUE TITLE
TypeError: jQuery(...).validateCreditCard

### ISSUE THREAD

**Issue by advokatb** [strangerstudios/pmpro-multiple-memberships-per-user#37]
Hi. I've got the error below in browser console that breaks other scripts on my site.
```
Uncaught TypeError: jQuery(...).validateCreditCard is not a function
    at HTMLDocument.<anonymous> (pmprommpu-checkout.js?ver=.5:152)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
```
When I comment this function then I can't buy two membership levels at once.
Using WordPress 4.9.9 and the latest Paid Membership Pro version.

Please help.

P.S. I use this plugin with WooCommerce Paid Membership Pro addon so I do not need card's validation.

Maybe I need updated version of jQuery?...

@dchenk maybe you can help? Thanks.

**Comment by francyesco-epsilon** [comment]
have you found a fix? what theme are you using?

**Comment by JarrydLong** [comment]
There's a couple of duplicate issues open regarding this issue. Lets continue the discussion in #92
