### ISSUE TITLE
Problem with displaying membership groups

### ISSUE THREAD

**Issue by MikeWitts** [strangerstudios/pmpro-multiple-memberships-per-user#7]
In the admin pages the membership groups always display as blank. This is also the case when viewing a specific users membership levels. See attached.

Functionality other than this still works as expected and database shows levels and groups correctly.
<img width="1279" alt="2d0f990e63b04a132c39285d47714ce1" src="https://cloud.githubusercontent.com/assets/26459656/24579313/a35d80f8-16ea-11e7-8299-6b9d9648d3e9.png">

**Comment by AAnkudovich** [comment]
Mike My issue went away after fixing back ticks like mentioned here https://github.com/strangerstudios/pmpro-multiple-memberships-per-user/pull/5/files

**Comment by MikeWitts** [comment]
Hi Artem, I managed to resolve the issue myself by doing the same! Thank you for your response!
