### ISSUE TITLE
Members can't cancel memberships with 6.5

### ISSUE THREAD

**Issue by thebioguy** [strangerstudios/pmpro-multiple-memberships-per-user#83]
Members can't cancel memberships with 6.5 and Buddypress integration.

**Comment by thebioguy** [comment]
In 6.3, if a member/user cancels one membership, they are all canceled.

**Comment by andrewlimaza** [comment]
This issue should be resolved with the latest version of MMPU, if you still experience this issue please do not hesitate to open a new issue.
