### ISSUE TITLE
Change membership level only works with primary language

### ISSUE THREAD

**Issue by changemakr** [strangerstudios/pmpro-multiple-memberships-per-user#87]
Hello,

I have installed the plugin and the idea is FANTASTIC and works perfekt, but....
When I select my secondary language(German) on my two-languages site, I can select multiple levels at once, but in my settings this is disabled and the checkout button is too disabled and where it's really odd is that all works with the sites primary language(English) selected...

Hope you can help us

Regards
Asger Frisgård
Make Group ApS

**Comment by andrewlimaza** [comment]
Hi Asger,

You may download the latest version of MMPU here -> https://github.com/strangerstudios/pmpro-multiple-memberships-per-user

This has the updated .pot file that may be used with a plugin like Loco Translate to translate the text of MMPU. Please do not hesitate to reach out if you still are facing issues with this.

For any support, please open a ticket at https://www.paidmembershipspro.com/support
