### ISSUE TITLE
MMPU, PMPro and Paypal Exress

### ISSUE THREAD

**Issue by TestDen** [strangerstudios/pmpro-multiple-memberships-per-user#88]
Hello,

We have setup the MMPU with PMPRO and it was working with Paypal until we enabled users to purchase more then one "membership" and do one checkout/payment. This works with braintree, has anyone figure out how to fix and make the total payment pass through to PayPal? Right now it only sends through 1 payment, but adds all the selected memberships.

Thanks!

**Comment by andrewlimaza** [comment]
Hi @TestDen 

PayPal does not allow multiple subscriptions (via API) within a single checkout. This is a limitation of PayPal and you would need to let user's purchase one level at a time when using PayPal. 

Unfortunately there is no way around this.
