### ISSUE TITLE
Uncaught TypeError: jQuery(...).validateCreditCard is not a function

### ISSUE THREAD

**Issue by francyesco-epsilon** [strangerstudios/pmpro-multiple-memberships-per-user#92]
after enabling the plugin v0.7 it gives this js error that break some page, i'm using Boss. theme

**Comment by jveseabra** [comment]
Hey, any fix for that yet? I have the same error over here.

**Comment by andrewlimaza** [comment]
Hi @jveseabra 

Are you still facing this issue after the latest update?

If so, please can you let me know what plugins you are using and if you have any custom code or custom page templates for PMPro.

**Comment by michaelbeil** [comment]
Console error came up in ticket 471660 on PHP 8.0.27, but I was able to purchase a subscription product without any error with PHP 7.4.30, and 8.1.6.

Console error from pmpro-checkout.js on customer site using Multiple Memberships per User Add On 0.8.3:


> Uncaught TypeError: jQuery(…).validateCreditCard is not a function
> at HTMLDocument.<anonymous> (pmprommpu-checkout.js?ver=0.8.2:152:30)
> at e (jquery.min.js?ver=3.6.1:2:30038)
> at t (jquery.min.js?ver=3.6.1:2:30340)

The error goes away when MMPU is deactivated.
