### ISSUE TITLE
Price logic in woocommerce

### ISSUE THREAD

**Issue by ArmandoValencia** [strangerstudios/pmpro-multiple-memberships-per-user#93]
Hi. v0.7 has some troubles showing correct prices when using woocommerce.
![image](https://user-images.githubusercontent.com/17320206/99739076-8da5a600-2a91-11eb-9bd6-8d3c54e4cdd0.png)

 If user has memberships with two different prices, how to manage to use the lowest price of them? What's the logic behind it?

**Comment by andrewlimaza** [comment]
Hi @ArmandoValencia 

Here is a pre-release for WooCommerce and Multiple Memberships Per User - https://github.com/strangerstudios/pmpro-woocommerce/pull/176

This will automatically discount with the better discount if a member holds more than one membership level. I am going to close this ticket as this PR is set to be merged and released in the near future.
